apiVersion: "1.0.4"
namespace: poc-pipelines
createNamespace: true
customLabels: "smc.cypress-secrets-secrets=true"

configuration:
  gitCredentialsSecret: github-credentials
  tektonDashboardURL: https://tekton.cdnpk.net
  sendmailSender: jarvis@freepik.com
  configuration.artifactsEnabled: false
  cloneDepth: 20
  nodeSelector:
    machine_type: n2d-standard-4
  tolerations:
  - key: "type"
    operator: "Equal"
    value: "pipelines"
    effect: "NoSchedule"

echo: &echo
  description: just a test step
  image: alpine
  script: |
    #!/usr/bin/env sh
    echo "just a test step"

pipelines:
  branches:

  - name: development
    regex: ^feature\/.*$
    serviceAccount: poc-pipelines
    nextPipeline: {}
    steps:
    - name: echo
      !!merge <<: *echo

  - name: producction
    regex: ^main$
    serviceAccount: poc-pipelines
    nextPipeline: {}
    steps:
    - name: echo
      !!merge <<: *echo
